package com.school.nfcard.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.school.nfcard.entity.ClassInfo;
import com.school.nfcard.entity.SchoolInfo;
import com.school.nfcard.entity.Student;

import com.school.nfcard.greendao.ClassInfoDao;
import com.school.nfcard.greendao.SchoolInfoDao;
import com.school.nfcard.greendao.StudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig classInfoDaoConfig;
    private final DaoConfig schoolInfoDaoConfig;
    private final DaoConfig studentDaoConfig;

    private final ClassInfoDao classInfoDao;
    private final SchoolInfoDao schoolInfoDao;
    private final StudentDao studentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        classInfoDaoConfig = daoConfigMap.get(ClassInfoDao.class).clone();
        classInfoDaoConfig.initIdentityScope(type);

        schoolInfoDaoConfig = daoConfigMap.get(SchoolInfoDao.class).clone();
        schoolInfoDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        classInfoDao = new ClassInfoDao(classInfoDaoConfig, this);
        schoolInfoDao = new SchoolInfoDao(schoolInfoDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);

        registerDao(ClassInfo.class, classInfoDao);
        registerDao(SchoolInfo.class, schoolInfoDao);
        registerDao(Student.class, studentDao);
    }
    
    public void clear() {
        classInfoDaoConfig.clearIdentityScope();
        schoolInfoDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
    }

    public ClassInfoDao getClassInfoDao() {
        return classInfoDao;
    }

    public SchoolInfoDao getSchoolInfoDao() {
        return schoolInfoDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

}
